### ISSUE TITLE
Get gi.repository error with stock repo

### ISSUE THREAD

**Issue by WryOpussum** [zevlee/hello-world-gtk#1]
Traceback (most recent call last):
  File "hello-world-gtk", line 4, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "lib/application.py", line 5, in <module>
ModuleNotFoundError: No module named 'gi.repository'
[15447] Failed to execute script 'hello-world-gtk' due to unhandled exception!

I got this when trying to compile my own code aswell. Is this a known issue?

**Comment by zevlee** [comment]
It looks like PyGObject is not installed. Which OS are you using?

**Comment by WryOpussum** [comment]
Fedora. Did some research and i figured out it was a pyinstaller issue. I opened up a issue there and i did what they said i should do. Prob should close this issue. Btw i got it working via creating a venv. Thank you for your repo btw.

**Comment by zevlee** [comment]
Thanks to https://github.com/pyinstaller/pyinstaller/pull/6869, the base repository now works on Fedora-based systems without issue. @WryOpussum

**Comment by WryOpussum** [comment]
Cool. Will test it out!
